[package]
name = "smdp"
version = "0.1.0"
edition = "2024"

[dev-dependencies]
rand = "0.8"

[dependencies]
anyhow = "1.0.98"
bitfield = "0.19.1"
bytes = "1.10.1"
serialport = "4.7.2"
thiserror = "2.0.12"
tokio = {version="1.46.1", features=["io-std", "io-util"]}
